---
- name: install apache
  tasks:
    - name: install apache
      package: 
        name: httpd
        state: latest
    - name: start and enable apache
      systemd:
        name: httpd
        state: started
        enable: yes
    - name: identify the ip of host
      shell: "ip addr show eth0 | grep inet | awk '{ print $2; }' | sed 's/\/.*$//'"
      register: ip_of_server
    - debug:
        var: ip_of_server

